---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: storage
  resources:
    requests:
      storage: 1Gi
