---
- hosts: all
  become: true
  tasks:
  - name: Install packages for microk8s
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: true
    vars:
      packages:
        - docker
        - docker-compose
      notify:
        - docker status

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      group: docker

  - name: Install microk8s snap
    snap:
      name: microk8s
      classic: true
      channel: 1.19

  - name: Add vagrant user to microk8s group
    user:
      name: vagrant
      group: microk8s

  - name: Setup kubeconfig for vagrant user
    command: "{{ item }}"
    with_items:
      - usermod -g vagrant vagrant
      - usermod -a -G microk8s vagrant
      - microk8s status --wait-ready
      - sudo chown -f -R $USER ~/.kube

  - name: source bash profiles
    shell: source ~/.bashrc
    args:
      executable: /bin/bash


  - name: Generate join command
    command: sudo microk8s add-node
    become: false
    register: join_command

  - name: Copy join command to local file
    become: false
    local_action: copy content="{{ join_command.stdout_lines[5] }}" dest="./join-command"


  handlers:
    - name: docker status
      service: name=docker state=started
